# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import routes_pb2 as routes__pb2


class RoutesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGreeting = channel.unary_unary(
                '/router.Routes/GetGreeting',
                request_serializer=routes__pb2.Language.SerializeToString,
                response_deserializer=routes__pb2.Greeting.FromString,
                )


class RoutesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGreeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGreeting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGreeting,
                    request_deserializer=routes__pb2.Language.FromString,
                    response_serializer=routes__pb2.Greeting.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'router.Routes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Routes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGreeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/router.Routes/GetGreeting',
            routes__pb2.Language.SerializeToString,
            routes__pb2.Greeting.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
